name: Upload

on:
  push:
#    branches:
#      - "main"

jobs:
  charmhub-upload:
    runs-on: ubuntu-22.04
    name: Charmhub upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: whatever
        run: |
          /usr/bin/sudo snap install charmcraft --classic --channel latest/stable
          /usr/bin/sudo charmcraft pack --destructive-mode --verbose

#        with:
#          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
#          github-token: "${{ secrets.GITHUB_TOKEN }}"
#          channel: "edge"
#          upload-image: "false"
