name: Upload

on:
  push:
#    branches:
#      - "main"

jobs:
  charmhub-upload:
    runs-on: ubuntu-20.04
    name: Charmhub upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: whatever
        run: charmcraft pack --verbose
#        with:
#          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
#          github-token: "${{ secrets.GITHUB_TOKEN }}"
#          channel: "edge"
#          upload-image: "false"
